pipeline {
    agent any

    triggers {
        cron('* 1 * * *')
    }

    stages {

        stage('Example shell script') {
            steps {
                sh 'echo "WOO"'
            }
        }
    }

}
