pipeline {
    agent any

    triggers {
        cron('H/2 * * * *')
    }

    stages {

        stage('Example shell script') {
            steps {
                sh 'echo "WOO"'
            }
        }
    }

}
