pipeline {
    agent any

    environment {

        FOO = "BAR"

    }

    triggers {
        cron('H/2 * * * *')
    }

    stages {

        stage('Example shell script') {
            steps {

                script {
                    def result = 'YES'
                }

                sh 'echo "WOO"'
                sh "echo $result"
                sh "echo $FOO"
            }
        }
    }

}
